#!/usr/bin/env python3
"""Collect operating-system, Python, hardware, and package versions for reproducibility."""
from __future__ import annotations

import importlib
import importlib.metadata
import json
import platform
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKAGES = [
    ("numpy", "numpy"),
    ("pandas", "pandas"),
    ("torch", "torch"),
    ("dgl", "dgl"),
    ("dgllife", "dgllife"),
    ("rdkit", "rdkit"),
    ("scikit-learn", "sklearn"),
    ("scipy", "scipy"),
    ("matplotlib", "matplotlib"),
    ("seaborn", "seaborn"),
    ("networkx", "networkx"),
    ("tqdm", "tqdm"),
    ("easydict", "easydict"),
    ("hyperopt", "hyperopt"),
    ("optuna", "optuna"),
    ("xgboost", "xgboost"),
    ("tensorflow", "tensorflow"),
    ("joblib", "joblib"),
]


def version_of(module_name: str, distribution_name: str | None = None):
    try:
        mod = importlib.import_module(module_name)
    except Exception as exc:
        return f"NOT AVAILABLE ({type(exc).__name__}: {exc})"

    version = getattr(mod, "__version__", None)
    if version is not None:
        return str(version)

    # Some packages (e.g. EasyDict) do not expose __version__.
    # Fall back to installed distribution metadata.
    for candidate in (distribution_name, module_name):
        if not candidate:
            continue
        try:
            return importlib.metadata.version(candidate)
        except importlib.metadata.PackageNotFoundError:
            pass
    return "installed; version metadata unavailable"


def command_output(cmd):
    try:
        return subprocess.check_output(cmd, text=True, stderr=subprocess.STDOUT).strip()
    except Exception:
        return None


def main():
    data = {
        "platform": platform.platform(),
        "system": platform.system(),
        "release": platform.release(),
        "machine": platform.machine(),
        "processor": platform.processor(),
        "python": sys.version.replace("\n", " "),
        "packages": {display: version_of(module, display) for display, module in PACKAGES},
    }
    try:
        import torch
        data["cuda_available"] = torch.cuda.is_available()
        data["torch_cuda"] = torch.version.cuda
        data["cudnn"] = torch.backends.cudnn.version() if torch.backends.cudnn.is_available() else None
        data["gpu_count"] = torch.cuda.device_count()
        data["gpus"] = [torch.cuda.get_device_name(i) for i in range(torch.cuda.device_count())]
    except Exception as exc:
        data["torch_hardware_error"] = str(exc)
    nvidia_smi = command_output(["nvidia-smi", "--query-gpu=name,driver_version,memory.total", "--format=csv,noheader"])
    if nvidia_smi:
        data["nvidia_smi"] = nvidia_smi.splitlines()

    out_json = ROOT / "environment" / "tested_environment.json"
    out_md = ROOT / "environment" / "TESTED_ENVIRONMENT.md"
    out_json.parent.mkdir(parents=True, exist_ok=True)
    out_json.write_text(json.dumps(data, indent=2), encoding="utf-8")

    lines = [
        "# Tested environment",
        "",
        "> Generated by `python tools/collect_environment.py` on the machine used for validation.",
        "",
        f"- Operating system: {data['platform']}",
        f"- Architecture: {data['machine']}",
        f"- Python: {data['python']}",
        f"- CUDA available: {data.get('cuda_available', 'unknown')}",
        f"- CUDA reported by PyTorch: {data.get('torch_cuda', 'unknown')}",
        f"- cuDNN: {data.get('cudnn', 'unknown')}",
        f"- GPUs: {', '.join(data.get('gpus', [])) if data.get('gpus') else 'none detected'}",
        "",
        "## Package versions",
        "",
    ]
    for name, version in data["packages"].items():
        lines.append(f"- {name}: {version}")
    out_md.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(out_md)
    print(out_json)


if __name__ == "__main__":
    main()
